name: React-Js
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:    
          node-version: '18'
      - name: Install Dependencies
        run: npm ci    # same as run install but ci will install what you have in the package.json
      - name: Run Tests
        run: npm test
      # - name: Print GoodBye
      #   run: echo "Bye Bye"
